### ISSUE TITLE
is there a way to keep the rdp running after 6 hours?

### ISSUE THREAD

**Issue by ali-farhad** [nelsonjchen/reverse-rdp-windows-github-actions#11]
hello sir,
thanks for this awesome project. 

is there any way to keep this rdp running for more than 6 hours?

**Comment by nelsonjchen** [comment]
nope. These are only meant for automated tasks less than 6 hours long.

**Comment by AmirulAndalib** [comment]
# will github ban me for this?

**Comment by ali-farhad** [comment]
> # will github ban me for this?

most probably no. they are providing these machines as a part of their cloud functions

**Comment by AmirulAndalib** [comment]
## i saw some of my friends getting banned for running windows 10 on github action but is this due to massive usage/they wont allow these kinds of tricks i am aware and scared 😯
