### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by alexdanca** [nelsonjchen/reverse-rdp-windows-github-actions#15]
![Screenshot_20210711-170724_Chrome.jpg](https://user-images.githubusercontent.com/55664587/125199538-50d02e80-e26f-11eb-9a11-2b7b21c844a6.jpg)

Rezolved and NOT = N

**Comment by nelsonjchen** [comment]
Uh, that's not my software at all.

**Comment by alexdanca** [comment]
Sorry is simple project
is it possible to keep rdp windows activated for more than 6 hours??
