### ISSUE TITLE
Support for Ubuntu and macOS

### ISSUE THREAD

**Issue by FaithfulYoshi** [nelsonjchen/reverse-rdp-windows-github-actions#2]
GitHub also provides Ubuntu and macOS as an option for the virtual environment. Is there a way to enable RDP on these operating systems?

**Comment by nelsonjchen** [comment]
There is a way, I think, but it's quite complicated. The situation is different for Ubuntu and macOS. The biggest difference is that macOS includes a desktop environment and Ubuntu does not. That said, if you really, really, really, really need RDP...

First, RDP is practically proprietary to Microsoft stuff even though Microsoft is submitting patches and documentation to FOSS RDP implementations. You're more likely to find someway to use VNC to connect to the graphical desktop. There do exist VNC to RDP bridges. I have no experience with those.

For macOS, it's somewhat non-headless and there's a Desktop you can VNC into with these steps: 

https://github.com/dakotaKat/fastmac-VNCgui

I haven't tried it though. You can probably pair it with some bridge if you need VNC to RDP.

For Ubuntu, where there is no desktop environment, most people just SSH or get access to the shell. If you're dealing with that, you can probably get away with just tunshell.com . If you *must* have a desktop envionment, you can probably install a desktop environment, expose it over VNC or if RDP is required, use [xrdp](http://xrdp.org/) to provide a X11 server and forward the RDP ports so they are publically accessible with something like ngrok.

**Comment by nelsonjchen** [comment]
I'll edit and mention fastmac-VNCgui and tunshell in the readme. I think that should about cover the "other" runners if someone were to stumble on this and wanted to know the equivalents or similar projects.
